.github/project.yml

This will include the openapi improvement #9

Create release 0.0.5

---

README.md

I added a adoc format image, this PR fix it to be md

Fix image in README

---

runtime/src/main/java/io/quarkiverse/loggingmanager/stream/JsonHandler.java
ui/src/main/webapp/logging-manager/index.html
ui/src/main/webapp/logging-manager/loggingmanager.js

Fix #38
This PR adds
- a new icon that allows a user to select the columns that should be visible in the log. 
- the ability to remember the state (zoom level, follow log, columns etc)
- add a linebreak on Enter press

Display selected columns

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerUIConfig.java
runtime/src/main/java/io/quarkiverse/loggingmanager/stream/HistoryHandler.java
runtime/src/main/java/io/quarkiverse/loggingmanager/stream/LogstreamSocket.java
runtime/src/main/java/io/quarkiverse/loggingmanager/stream/WebSocketHandler.java
ui/src/main/webapp/logging-manager/index.html
ui/src/main/webapp/logging-manager/loggingmanager.js
ui/src/main/webapp/logging-manager/style.css

When starting the log, you now get some history. 
Also :
- made the WS URL configurable and under the non-application path
- added Shift+Scroll to zoom in and out
- added line spacing with Shift+Up/Down
- added information section to display messages for a moment
Fix #39 
Fix #27 
Fix #48
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

History to the log and other changes

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerConfig.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerOpenAPIFilter.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerUIConfig.java
deployment/src/main/resources/dev-templates/embedded.html
deployment/src/test/java/io/quarkiverse/loggingmanager/deployment/CustomConfigTest.java
pom.xml
runtime/src/main/java/io/quarkiverse/loggingmanager/LoggerManagerRecorder.java

This PR contains changes needed to run against Quarkus 1.12.1 due to /q path changes.

Update to 1.12.1

---

.github/workflows/build.yml
.github/workflows/release.yml

Update build scripts to support main branch

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerConfig.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java

Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

Make history configurable

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
deployment/src/main/resources/META-INF/resources/template/loggermanager.html

Fix #69
Signed-off-by:Phillip Kruger <phillip.kruger@gmail.com>

Fixes for Quarkus 1.13.0.Final

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
runtime/src/main/resources/META-INF/quarkus-extension.yaml

Fix native issue

---

pom.xml

Signed-off-by: Phillip Kruger <phillip.kruger@gmail.com>

version updates

---

.github/project.yml
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
pom.xml

Attempting to resolve #198 
Please let me know if I should amend my commit to not change the `project.yml`
Please note from the logs in the quarkus issue:
```
[ERROR] Errors: 
[ERROR]   SmsMessageAddedConsumerTest.testConsumingSmsMessage » Runtime java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
[error]: Build step io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor#includeUiAndWebsocket threw an exception: java.lang.NoSuchMethodError: 'io.quarkus.bootstrap.model.AppModel io.quarkus.deployment.pkg.builditem.CurateOutcomeBuildItem.getEffectiveModel()'
at io.quarkiverse.loggingmanager.deployment.LoggingManagerProcessor.includeUiAndWebsocket(LoggingManagerProcessor.java:152)
```
@phillip-kruger

Attempting to Resolve NoSuchMethodError in Quarkus 3.1.0.Final

---

deployment/pom.xml
pom.xml
runtime/pom.xml

Relates to #187 
This is more to get the ball rolling. The dev-ui portion obviously isn't working with this pr, it just makes the extension compile with quarkus 3. UT are passing, and REST functionality is working, which is actually what I do use in my production app.
I do not think I have the competence to do the UI portion, unless I get really good pointers.
cc @phillip-kruger

Move to quarkus 3

---

pom.xml

Bumps `quarkus.version` from 3.0.3.Final to 3.2.0.Final
Bumps `quarkiverse-parent` from 14 to 15

Bump quarkus.version and quarkiverse-parent

---

pom.xml

bump quarkus version

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
deployment/src/main/resources/META-INF/resources/template/loggermanager.html

Fix Dev UI Urls

---

deployment/pom.xml
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/devui/LoggingManagerDevUIProcessor.java
deployment/src/main/resources/dev-ui/qwc-logging-manager-loggers.js
deployment/src/test/java/io/quarkiverse/loggingmanager/deployment/devui/StaticDataDevUITest.java
runtime/src/main/java/io/quarkiverse/loggingmanager/LogController.java
runtime/src/main/java/io/quarkiverse/loggingmanager/devui/LoggingManagerJsonRpcService.java

[Draft] Migrate to new dev ui

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java

I would like to mak quarkus-logging-manager honor the managment interface, if enabled.
But I hardly understand the inner working of the Quarkus extension :(

Honor management interface if enabled

---

deployment/pom.xml
pom.xml

bump quarkus and maven surefire plugin versions

---

deployment/src/main/resources/dev-ui/qwc-logging-manager-loggers.js

I think this is right @phillip-kruger I looked at some other examples.  We should probably add filtering too since there can be a ton of loggers.

DevUI: Add sorting to table columns

---

README.md
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/devui/LoggingManagerDevUIProcessor.java
deployment/src/main/resources/dev-ui/qwc-logging-manager-loggers.js

DevUI: Add filtering

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java

Fix #348: Remove management config check

Fix #348: Remove management config check

---

runtime/src/main/java/io/quarkiverse/loggingmanager/LoggerHandler.java

Fix #354: Defend against POST invalid content type

Fix #354: Defend against POST invalid content type

---

deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerOpenAPIFilter.java
deployment/src/main/java/io/quarkiverse/loggingmanager/deployment/LoggingManagerProcessor.java
pom.xml

Similar fix to: https://github.com/quarkusio/quarkus/pull/47680

OpenAPI ensure consistent ordering
